name: Frontend CI/CD

on:
  push:
    branches:
      - dev-test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build and Deploy
        run: |
          npm run build
          rsync -av --delete -v dist/ adde22@ssh.student.bth.se:www/editor  # Replace with your deployment command
