name: Backend CI/CD

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.20.2

            - name: Install backend dependencies
              working-directory: backend-mongodb # Specify the backend directory
              run: npm install

            - name: Run backend tests
              working-directory: backend-mongodb # Specify the backend directory
              run: npm test
