name: Frontend Tests

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.20.2

            - name: Install dependencies
              run: npm install

            - name: Install dotenv package
              run: npm install dotenv --save-dev

            - name: Run Selenium tests
              working-directory: frontend-vue # Specify the backend directory
              run: npm test -- --verbose
              env:
                  CHROME_BIN: /usr/bin/google-chrome
                  CHROME_DRIVER_PATH: /usr/local/bin/chromedriver
