name: Frontend CI/CD

on:
    push:
        branches:
            - dev-test

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.20.2

            - name: Install frontend dependencies
              working-directory: frontend-vue # Specify the frontend directory
              run: npm install

            - name: Run frontend tests
              working-directory: frontend-vue # Specify the frontend directory
              run: npm test
