name: Frontend Tests

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.20.2

            - name: Install dependencies
              run: npm install

            - name: List /usr/local/bin/
              run: ls -l /usr/local/bin/

            - name: Run Selenium tests
              run: npm test
              env:
                  CHROME_BIN: /usr/bin/google-chrome
                  CHROME_DRIVER_PATH: /usr/local/bin/chromedriver

            - name: Run Selenium tests
              run: npm test -- --verbose
              env:
                  CHROME_BIN: /usr/bin/google-chrome
                  CHROME_DRIVER_PATH: /usr/bin/chromedriver
